// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4WoEA3IX-HRTU7kvOGIQl7F4ZDWFH78o',
    appId: '1:1038529005216:web:b5645d213625c746936bc5',
    messagingSenderId: '1038529005216',
    projectId: 'portfolio-projesi-a5027',
    authDomain: 'portfolio-projesi-a5027.firebaseapp.com',
    storageBucket: 'portfolio-projesi-a5027.appspot.com',
    measurementId: 'G-F1YJ595ZSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWEw2_p6hQNdGBPEqD8BXuqaqLXvS91ws',
    appId: '1:1038529005216:android:12c8d19bbfae1ec1936bc5',
    messagingSenderId: '1038529005216',
    projectId: 'portfolio-projesi-a5027',
    storageBucket: 'portfolio-projesi-a5027.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuC1nkjSDDIAd5rHY4O9L-ai4ln1fIj40',
    appId: '1:1038529005216:ios:31eb326af6b54016936bc5',
    messagingSenderId: '1038529005216',
    projectId: 'portfolio-projesi-a5027',
    storageBucket: 'portfolio-projesi-a5027.appspot.com',
    iosBundleId: 'com.akkayasoft.portfolio.akkayasoftPortfolioProjesi',
  );
}
